services:
  builder:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: build
    environment:
      XDEBUG_MODE: coverage
    volumes:
      - ../app:/app
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: dev
      args:
        HOST_UID: ${HOST_UID-1000}
        GROUP_ID: ${HOST_GID-1000}
    container_name: app
    environment:
      XDEBUG_MODE: debug,develop,coverage
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    volumes:
      - ../app:/app
    tty: true
    stdin_open: true
